version: '3'

services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: "cost_manager"
      POSTGRES_USER: "cost_manager"
      POSTGRES_PASSWORD: "hidden"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    env_file: web/pyproject.toml
    environment:
      DEBUG: 'true'
    command: poetry run gunicorn cost_manager.wsgi:application -w 2 -b :8000

volumes:
  web-django:
  web-static:
  pgdata:
  redisdata:
