# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2003(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, category: str=None, description: str=None, amount: int=None, kind: str=None, user: str=None):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger

        :param id: The id of this InlineResponse2003.  # noqa: E501
        :type id: int
        :param category: The category of this InlineResponse2003.  # noqa: E501
        :type category: str
        :param description: The description of this InlineResponse2003.  # noqa: E501
        :type description: str
        :param amount: The amount of this InlineResponse2003.  # noqa: E501
        :type amount: int
        :param kind: The kind of this InlineResponse2003.  # noqa: E501
        :type kind: str
        :param user: The user of this InlineResponse2003.  # noqa: E501
        :type user: str
        """
        self.swagger_types = {
            'id': int,
            'category': str,
            'description': str,
            'amount': int,
            'kind': str,
            'user': str
        }

        self.attribute_map = {
            'id': 'id',
            'category': 'category',
            'description': 'description',
            'amount': 'amount',
            'kind': 'kind',
            'user': 'user'
        }
        self._id = id
        self._category = category
        self._description = description
        self._amount = amount
        self._kind = kind
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2003':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.  # noqa: E501
        :rtype: InlineResponse2003
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this InlineResponse2003.


        :return: The id of this InlineResponse2003.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this InlineResponse2003.


        :param id: The id of this InlineResponse2003.
        :type id: int
        """

        self._id = id

    @property
    def category(self) -> str:
        """Gets the category of this InlineResponse2003.


        :return: The category of this InlineResponse2003.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this InlineResponse2003.


        :param category: The category of this InlineResponse2003.
        :type category: str
        """

        self._category = category

    @property
    def description(self) -> str:
        """Gets the description of this InlineResponse2003.


        :return: The description of this InlineResponse2003.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this InlineResponse2003.


        :param description: The description of this InlineResponse2003.
        :type description: str
        """

        self._description = description

    @property
    def amount(self) -> int:
        """Gets the amount of this InlineResponse2003.


        :return: The amount of this InlineResponse2003.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this InlineResponse2003.


        :param amount: The amount of this InlineResponse2003.
        :type amount: int
        """

        self._amount = amount

    @property
    def kind(self) -> str:
        """Gets the kind of this InlineResponse2003.


        :return: The kind of this InlineResponse2003.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind: str):
        """Sets the kind of this InlineResponse2003.


        :param kind: The kind of this InlineResponse2003.
        :type kind: str
        """

        self._kind = kind

    @property
    def user(self) -> str:
        """Gets the user of this InlineResponse2003.


        :return: The user of this InlineResponse2003.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this InlineResponse2003.


        :param user: The user of this InlineResponse2003.
        :type user: str
        """

        self._user = user
