# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, access: str=None, refresh: str=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param access: The access of this InlineResponse2001.  # noqa: E501
        :type access: str
        :param refresh: The refresh of this InlineResponse2001.  # noqa: E501
        :type refresh: str
        """
        self.swagger_types = {
            'access': str,
            'refresh': str
        }

        self.attribute_map = {
            'access': 'access',
            'refresh': 'refresh'
        }
        self._access = access
        self._refresh = refresh

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access(self) -> str:
        """Gets the access of this InlineResponse2001.


        :return: The access of this InlineResponse2001.
        :rtype: str
        """
        return self._access

    @access.setter
    def access(self, access: str):
        """Sets the access of this InlineResponse2001.


        :param access: The access of this InlineResponse2001.
        :type access: str
        """

        self._access = access

    @property
    def refresh(self) -> str:
        """Gets the refresh of this InlineResponse2001.


        :return: The refresh of this InlineResponse2001.
        :rtype: str
        """
        return self._refresh

    @refresh.setter
    def refresh(self, refresh: str):
        """Sets the refresh of this InlineResponse2001.


        :param refresh: The refresh of this InlineResponse2001.
        :type refresh: str
        """

        self._refresh = refresh
