# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse400(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, uid: int=None, token: str=None):  # noqa: E501
        """InlineResponse400 - a model defined in Swagger

        :param uid: The uid of this InlineResponse400.  # noqa: E501
        :type uid: int
        :param token: The token of this InlineResponse400.  # noqa: E501
        :type token: str
        """
        self.swagger_types = {
            'uid': int,
            'token': str
        }

        self.attribute_map = {
            'uid': 'uid',
            'token': 'token'
        }
        self._uid = uid
        self._token = token

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse400':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_400 of this InlineResponse400.  # noqa: E501
        :rtype: InlineResponse400
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uid(self) -> int:
        """Gets the uid of this InlineResponse400.


        :return: The uid of this InlineResponse400.
        :rtype: int
        """
        return self._uid

    @uid.setter
    def uid(self, uid: int):
        """Sets the uid of this InlineResponse400.


        :param uid: The uid of this InlineResponse400.
        :type uid: int
        """

        self._uid = uid

    @property
    def token(self) -> str:
        """Gets the token of this InlineResponse400.


        :return: The token of this InlineResponse400.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this InlineResponse400.


        :param token: The token of this InlineResponse400.
        :type token: str
        """

        self._token = token
