# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UsersActivationBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, uid: int=None):  # noqa: E501
        """UsersActivationBody - a model defined in Swagger

        :param uid: The uid of this UsersActivationBody.  # noqa: E501
        :type uid: int
        """
        self.swagger_types = {
            'uid': int
        }

        self.attribute_map = {
            'uid': 'uid'
        }
        self._uid = uid

    @classmethod
    def from_dict(cls, dikt) -> 'UsersActivationBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The users_activation_body of this UsersActivationBody.  # noqa: E501
        :rtype: UsersActivationBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uid(self) -> int:
        """Gets the uid of this UsersActivationBody.


        :return: The uid of this UsersActivationBody.
        :rtype: int
        """
        return self._uid

    @uid.setter
    def uid(self, uid: int):
        """Sets the uid of this UsersActivationBody.


        :param uid: The uid of this UsersActivationBody.
        :type uid: int
        """

        self._uid = uid
