# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UsersSetPasswordBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, new_password: str=None, re_new_password: str=None, current_password: str=None):  # noqa: E501
        """UsersSetPasswordBody - a model defined in Swagger

        :param new_password: The new_password of this UsersSetPasswordBody.  # noqa: E501
        :type new_password: str
        :param re_new_password: The re_new_password of this UsersSetPasswordBody.  # noqa: E501
        :type re_new_password: str
        :param current_password: The current_password of this UsersSetPasswordBody.  # noqa: E501
        :type current_password: str
        """
        self.swagger_types = {
            'new_password': str,
            're_new_password': str,
            'current_password': str
        }

        self.attribute_map = {
            'new_password': 'new_password',
            're_new_password': 're_new_password',
            'current_password': 'current_password'
        }
        self._new_password = new_password
        self._re_new_password = re_new_password
        self._current_password = current_password

    @classmethod
    def from_dict(cls, dikt) -> 'UsersSetPasswordBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The users_set_password_body of this UsersSetPasswordBody.  # noqa: E501
        :rtype: UsersSetPasswordBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def new_password(self) -> str:
        """Gets the new_password of this UsersSetPasswordBody.


        :return: The new_password of this UsersSetPasswordBody.
        :rtype: str
        """
        return self._new_password

    @new_password.setter
    def new_password(self, new_password: str):
        """Sets the new_password of this UsersSetPasswordBody.


        :param new_password: The new_password of this UsersSetPasswordBody.
        :type new_password: str
        """

        self._new_password = new_password

    @property
    def re_new_password(self) -> str:
        """Gets the re_new_password of this UsersSetPasswordBody.


        :return: The re_new_password of this UsersSetPasswordBody.
        :rtype: str
        """
        return self._re_new_password

    @re_new_password.setter
    def re_new_password(self, re_new_password: str):
        """Sets the re_new_password of this UsersSetPasswordBody.


        :param re_new_password: The re_new_password of this UsersSetPasswordBody.
        :type re_new_password: str
        """

        self._re_new_password = re_new_password

    @property
    def current_password(self) -> str:
        """Gets the current_password of this UsersSetPasswordBody.


        :return: The current_password of this UsersSetPasswordBody.
        :rtype: str
        """
        return self._current_password

    @current_password.setter
    def current_password(self, current_password: str):
        """Sets the current_password of this UsersSetPasswordBody.


        :param current_password: The current_password of this UsersSetPasswordBody.
        :type current_password: str
        """

        self._current_password = current_password
