# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UsersMeBody1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, current_password: str=None):  # noqa: E501
        """UsersMeBody1 - a model defined in Swagger

        :param current_password: The current_password of this UsersMeBody1.  # noqa: E501
        :type current_password: str
        """
        self.swagger_types = {
            'current_password': str
        }

        self.attribute_map = {
            'current_password': 'current_password'
        }
        self._current_password = current_password

    @classmethod
    def from_dict(cls, dikt) -> 'UsersMeBody1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The users_me_body_1 of this UsersMeBody1.  # noqa: E501
        :rtype: UsersMeBody1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current_password(self) -> str:
        """Gets the current_password of this UsersMeBody1.


        :return: The current_password of this UsersMeBody1.
        :rtype: str
        """
        return self._current_password

    @current_password.setter
    def current_password(self, current_password: str):
        """Sets the current_password of this UsersMeBody1.


        :param current_password: The current_password of this UsersMeBody1.
        :type current_password: str
        """

        self._current_password = current_password
