# Generated by Django 4.1.6 on 2023-02-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_remove_transaction_is_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='kind',
            field=models.CharField(default='Расход', max_length=24),
        ),
    ]
